# Generated by Django 4.2.3 on 2023-07-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizendocument',
            name='document',
            field=models.CharField(choices=[('', 'Select Document'), ('Passport', 'Passport'), ('Individual Descriptive Document', 'Individual Descriptive Document')], default='', max_length=50, verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='citizenparents',
            name='parent',
            field=models.CharField(choices=[('', 'Select Parent'), ('Father', 'Father'), ('Mother', 'Mother')], default='', max_length=10, verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='nid_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='National ID Number'),
        ),
        migrations.AlterField(
            model_name='documentapplication',
            name='documentCategories',
            field=models.CharField(blank=True, choices=[('', 'Select Document Category'), ('None', 'None'), ('Ordinary Passport', 'Ordinary Passport'), ('Diplomatic Passport', 'Diplomatic Passport'), ('Service Passport', 'Service Passport')], default='', max_length=50, null=True, verbose_name='Document Category'),
        ),
    ]
