# Generated by Django 4.2.3 on 2023-07-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_citizendocument_document_citizenparents_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Service Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
