# Generated by Django 4.2.3 on 2023-07-22 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_citizendocument_picture_citizendocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenaddress',
            name='citizen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='management.citizen', verbose_name='Citizen'),
        ),
    ]
