# Generated by Django 4.2.3 on 2023-07-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_citizenaddress_citizen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenaddress',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='citizenaddress',
            name='province',
            field=models.CharField(blank=True, max_length=50, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='citizenaddress',
            name='state',
            field=models.CharField(blank=True, max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='citizenaddress',
            name='street',
            field=models.CharField(blank=True, max_length=50, verbose_name='Street'),
        ),
    ]
