# Generated by Django 4.2.3 on 2023-07-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CitizenParents',
            new_name='CitizenParent',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
