# Generated by Django 4.2.3 on 2023-07-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_rename_citizenparents_citizenparent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='email',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='phone_number',
        ),
    ]
