# Generated by Django 4.2.3 on 2023-07-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_citizen_email_remove_citizen_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='picture',
        ),
    ]
