# Generated by Django 4.2.3 on 2023-08-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_application_alter_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('', 'Select Service'), ('e-Passport Application', 'e-Passport Application'), ('Individual Descriptive Document Application', 'Individual Descriptive Document Application')], default='', max_length=100, unique=True, verbose_name='Service Name'),
        ),
    ]
